### ISSUE TITLE
HALF WAVE RECTIFIER WITH & WITHOUT FILTERS_R1_Experiment Name_grammatical mistake

### ISSUE THREAD

**Issue by Tanutsk** [sajal243/Round-templates#1]
Experiment name should be grammatically correct.
The word should be find ripple factor and not finds. 
Or say calculate ripple factor.

**Comment by Tanutsk** [comment]
@sajal243 Experiment name should be grammatically correct.
Rectify the word find instead of finds.
Or say calculate ripple factor.

**Comment by sajal243** [comment]
I fix it , u can check it .
and thanks..
