### ISSUE TITLE
Experiment: HALF WAVE RECTIFIER WITH & WITHOUT FILTERS_R1_LO_Action verb is missing

### ISSUE THREAD

**Issue by Tanutsk** [sajal243/Round-templates#3]
1. LO_1: To study the concept of Half Wave Rectifier 
**Issues:** 
a. LO1 is vague and not specific. The measurable action verb is missing.
**Suggestion:**: LO_1: a. Student will be able to explain the working of half wave rectifier.
b. Identify the cognitive level of the LO from the action verb used. (in this case action verb used is explain).

2. LO_2: To determine its ripple factor.
**Issue:** Vague
**Suggestion:** LO2 can be modified as:
LO_2: To determine the ripple factor of a half-wave rectifier.
Identify the action verb in the LO and state its cognitive level.

**Comment by sajal243** [comment]
I fixed it!
